@props(['service', 'isFavorite' => false])

@php
    $professional = $service->professional;
    $isVerified = $professional?->hasVerifiedIdentity() ?? false;
    $hasReviews = (int) ($professional?->total_reviews ?? 0) > 0;
@endphp

<article {{ $attributes->merge(['class' => 'marketplace-service-card']) }}>
    <div class="marketplace-service-card__media">@if ($service->coverImage)<img src="{{ IlluminateSupportFacadesStorage::disk('public')->url($service->coverImage->path) }}" alt="{{ $service->coverImage->alt_text ?: $service->title }}" loading="lazy">@else<span class="marketplace-service-card__placeholder" aria-hidden="true"><i class="bi bi-tools"></i></span>@endif<div class="marketplace-service-card__favorite">@auth @if (auth()->user()->isClient())<form method="POST" action="{{ route('professional.favorite.toggle', $professional) }}">@csrf<button class="favorite-button {{ $isFavorite ? 'is-favorite' : '' }}" type="submit" aria-label="{{ $isFavorite ? 'Quitar de favoritos' : 'Guardar profesional en favoritos' }}" aria-pressed="{{ $isFavorite ? 'true' : 'false' }}"><i class="bi bi-heart{{ $isFavorite ? '-fill' : '' }}" aria-hidden="true"></i></button></form>@endif @else<a class="favorite-button" href="{{ route('login') }}" aria-label="Inicia sesión para guardar favoritos"><i class="bi bi-heart" aria-hidden="true"></i></a>@endauth</div></div>
    <div class="marketplace-service-card__body"><div class="d-flex align-items-start justify-content-between gap-2 mb-2"><span class="service-card__category mb-0">{{ $service->category?->name ?? 'Servicio' }}</span>@if ($isVerified)<x-ui.badge variant="verified" label="Verificado" dot />@endif</div><h2 class="marketplace-service-card__title"><a href="{{ route('marketplace.service', $service) }}">{{ $service->title }}</a></h2><p class="marketplace-service-card__professional"><i class="bi bi-person-circle" aria-hidden="true"></i> <a href="{{ route('professional.public-profile', $professional) }}">{{ $professional?->user?->name ?? 'Profesional Chambapp' }}</a></p><div class="marketplace-service-card__meta"><span><i class="bi bi-geo-alt" aria-hidden="true"></i> {{ $professional?->city ?: 'Cerca de ti' }}</span>@if ($hasReviews)<span><i class="bi bi-star-fill" aria-hidden="true"></i> <span class="visually-hidden">Calificación:</span>{{ number_format((float) $professional->average_rating, 1) }} ({{ $professional->total_reviews }})</span>@else<span>Nuevo · Sin reseñas</span>@endif</div><div class="marketplace-service-card__footer"><strong>{{ $service->formattedPrice() }}</strong><div class="d-flex flex-wrap justify-content-end gap-2"><a class="ui-button ui-button--outline ui-button--sm" href="{{ route('marketplace.service', $service) }}">Ver detalle</a><a class="ui-button ui-button--secondary ui-button--sm" href="{{ route('job-requests.create', $service) }}">Solicitar</a></div></div></div>
</article>
