@extends('layouts.public')

@section('title', 'Chambapp | Encuentra ayuda confiable cerca de ti')
@section('meta_description', 'Descubre profesionales y servicios verificados para resolver lo que necesitas.')

@section('content')
    <section id="inicio" class="home-hero py-5 py-lg-6">
        <div class="container"><div class="row align-items-center g-4 g-lg-5"><div class="col-12 col-lg-7">
            <p class="eyebrow mb-3"><span class="eyebrow__dot" aria-hidden="true"></span> Ayuda confiable, más cerca</p>
            <h1 class="display-title mb-3">¿Qué servicio <span>necesitas?</span></h1>
            <p class="hero-copy mb-4">Encuentra profesionales verificados para tu hogar, tu negocio y esos proyectos que quieres sacar adelante.</p>
            <form class="visual-search" method="GET" action="{{ route('marketplace.search') }}" aria-label="Buscar servicios"><i class="bi bi-search visual-search__icon" aria-hidden="true"></i><label class="visually-hidden" for="home-search">Busca un servicio</label><input id="home-search" name="q" type="search" placeholder="Ej. plomería, limpieza o diseño" autocomplete="off"><x-ui.button type="submit" size="sm">Buscar <i class="bi bi-arrow-up-right" aria-hidden="true"></i></x-ui.button></form>
            <div class="d-flex flex-column flex-sm-row gap-3 align-items-stretch align-items-sm-center mt-4"><x-ui.button href="{{ route('marketplace.categories') }}">Explorar servicios <i class="bi bi-arrow-down-right" aria-hidden="true"></i></x-ui.button><a class="text-link" href="#como-funciona">Conoce Chambapp <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div>
        </div><div class="col-12 col-lg-5"><x-ui.card class="hero-preview-card" padding="none"><div class="hero-preview-card__topline"><span class="hero-card__mini-brand">chambapp</span><x-ui.badge variant="success" label="Cerca de ti" dot /></div><div class="hero-preview-card__body"><span class="hero-preview-card__icon" aria-hidden="true"><i class="bi bi-tools"></i></span><p class="hero-card__label mb-2">Hoy puedes resolver</p><p class="hero-card__headline mb-0">Eso que llevas días posponiendo.</p></div><a class="service-preview text-decoration-none" href="{{ route('marketplace.search') }}"><span class="service-preview__icon" aria-hidden="true"><i class="bi bi-house-heart"></i></span><span><strong>Hogar y reparaciones</strong><small>Profesionales listos para ayudarte</small></span><i class="bi bi-arrow-up-right service-preview__arrow" aria-hidden="true"></i></a></x-ui.card></div></div></div>
    </section>

    <section id="categorias" class="section-space pt-4 pt-lg-5"><div class="container"><div class="section-heading d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">Explora</p><h2 class="section-title mb-2">¿En qué te podemos ayudar?</h2><p class="section-copy mb-0">Elige una categoría para descubrir nuevas posibilidades.</p></div><a class="section-heading__note text-decoration-none" href="{{ route('marketplace.categories') }}"><i class="bi bi-stars" aria-hidden="true"></i> Ver todas las categorías</a></div><div class="row g-3">
        @forelse ($categories as $category)<div class="col-6 col-md-4 col-lg-2"><a class="category-tile h-100" href="{{ route('marketplace.category', $category) }}"><span class="category-tile__icon"><i class="bi bi-{{ $category->icon ?: 'grid' }}" aria-hidden="true"></i></span><span class="category-tile__name">{{ $category->name }}</span><i class="bi bi-arrow-up-right category-tile__arrow" aria-hidden="true"></i></a></div>@empty<div class="col-12"><x-ui.empty-state icon="bi-grid" title="Categorías en preparación" description="Pronto podrás explorar servicios por categoría." /></div>@endforelse
    </div></div></section>

    <section id="profesionales" class="section-space bg-surface-subtle"><div class="container"><div class="section-heading mb-4"><p class="eyebrow mb-2">Talento que inspira confianza</p><h2 class="section-title mb-2">Conoce a profesionales destacados.</h2><p class="section-copy mb-0">Personas verificadas que harán posible tu próxima solución.</p></div><div class="row g-3 g-lg-4">
        @forelse ($professionals as $professional)<div class="col-12 col-md-6 col-lg-4"><x-ui.card class="professional-card h-100" padding="p-4"><div class="d-flex align-items-start justify-content-between gap-3 mb-3"><x-ui.avatar :user="$professional->user" :src="$professional->profile_photo" :name="$professional->user?->name" size="lg" /><x-ui.badge variant="verified" label="Verificado" /></div><h3 class="professional-card__name mb-1">{{ $professional->user?->name ?? 'Profesional Chambapp' }}</h3><p class="professional-card__bio mb-3">{{ $professional->bio ?: 'Listo para ayudarte con experiencia y atención cercana.' }}</p><div class="professional-card__meta mb-4"><span><i class="bi bi-star-fill" aria-hidden="true"></i> {{ (int) $professional->total_reviews > 0 ? number_format((float) $professional->average_rating, 1) : 'Sin reseñas' }}</span><span><i class="bi bi-geo-alt" aria-hidden="true"></i> {{ $professional->city ?: 'Cerca de ti' }}</span></div><x-ui.button variant="outline" class="w-100" href="{{ route('professional.public-profile', $professional) }}">Ver perfil</x-ui.button></x-ui.card></div>@empty<div class="col-12"><x-ui.empty-state icon="bi-person-badge" title="Profesionales en preparación" description="Estamos preparando perfiles para que puedas conocerlos." /></div>@endforelse
    </div></div></section>

    <section id="servicios" class="section-space"><div class="container"><div class="section-heading d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">Ideas para empezar</p><h2 class="section-title mb-2">Servicios listos para descubrir.</h2><p class="section-copy mb-0">Explora opciones publicadas por profesionales verificados.</p></div><x-ui.button variant="outline" href="{{ route('marketplace.search') }}">Ver todos</x-ui.button></div><div class="row g-3 g-lg-4">
        @forelse ($services as $service)<div class="col-12 col-md-6 col-lg-4"><x-ui.card class="service-card h-100 p-0 overflow-hidden" padding="none"><a class="service-card__cover-placeholder text-decoration-none" href="{{ route('marketplace.service', $service) }}"><i class="bi bi-wrench-adjustable" aria-hidden="true"></i></a><div class="p-4"><div class="d-flex justify-content-between align-items-center gap-2 mb-3"><span class="service-card__category">{{ $service->category?->name ?? 'Servicio' }}</span><span class="service-card__rating"><i class="bi bi-star-fill" aria-hidden="true"></i> {{ (int) $service->professional?->total_reviews > 0 ? number_format((float) $service->professional->average_rating, 1) : 'Nuevo' }}</span></div><h3 class="service-card__title mb-2"><a href="{{ route('marketplace.service', $service) }}">{{ $service->title }}</a></h3><p class="service-card__professional mb-3"><i class="bi bi-person-circle" aria-hidden="true"></i> {{ $service->professional?->user?->name ?? 'Profesional Chambapp' }}</p><div class="d-flex justify-content-between align-items-center gap-3"><strong class="service-card__price">{{ $service->formattedPrice() }}</strong><a class="btn btn-link p-0 text-decoration-none" href="{{ route('marketplace.service', $service) }}">Ver más <i class="bi bi-arrow-right" aria-hidden="true"></i></a></div></div></x-ui.card></div>@empty<div class="col-12"><x-ui.empty-state icon="bi-briefcase" title="Servicios en preparación" description="Pronto podrás explorar servicios publicados por profesionales verificados." /></div>@endforelse
    </div></div></section>

    <section id="como-funciona" class="section-space pt-0"><div class="container"><div class="row g-3 g-lg-4"><div class="col-12 col-lg-7"><x-ui.card class="how-it-works h-100" padding="p-4 p-lg-5"><p class="eyebrow mb-2">Cómo funciona</p><h2 class="section-title mb-4">Una conexión simple para hacer que suceda.</h2><div class="row g-3"><div class="col-12 col-md-4"><div class="step-item"><span>01</span><strong>Busca</strong><p>Cuéntanos qué necesitas.</p></div></div><div class="col-12 col-md-4"><div class="step-item"><span>02</span><strong>Conoce</strong><p>Explora opciones confiables.</p></div></div><div class="col-12 col-md-4"><div class="step-item"><span>03</span><strong>Resuelve</strong><p>Da el siguiente paso.</p></div></div></div></x-ui.card></div><div class="col-12 col-lg-5"><x-ui.card class="professional-cta h-100" padding="p-4 p-lg-5"><span class="professional-cta__icon"><i class="bi bi-person-workspace" aria-hidden="true"></i></span><h2 class="h3 mt-4 mb-2">¿Tienes una habilidad que compartir?</h2><p class="section-copy mb-4">Crea tu perfil profesional y publica tus servicios.</p>@guest<x-ui.button href="{{ route('register') }}" variant="secondary">Crear cuenta <i class="bi bi-arrow-right" aria-hidden="true"></i></x-ui.button>@else<x-ui.button href="{{ route(auth()->user()->dashboardRoute()) }}" variant="secondary">Ir a mi espacio <i class="bi bi-arrow-right" aria-hidden="true"></i></x-ui.button>@endguest</x-ui.card></div></div></div></section>
@endsection
