@extends('layouts.public')

@section('title', 'Chambapp | Encuentra al profesional perfecto para tu chamba')
@section('meta_description', 'Conecta con profesionales verificados cerca de ti. Rápido, seguro y confiable.')

@section('content')
    <section id="inicio" class="hero-landing">
        <div class="container"><div class="row align-items-center g-4 g-xl-5"><div class="col-12 col-lg-6">
            <span class="hero-landing__kicker"><i class="bi bi-stars"></i> Chambas ahora, soluciones al instante</span>
            <h1 class="hero-landing__title">Encuentra al profesional <span>perfecto</span> para tu chamba</h1>
            <p class="hero-landing__copy">Conecta con profesionales verificados cerca de ti. Rápido, seguro y confiable.</p>
            <div class="hero-landing__actions">@auth @if (auth()->user()->isClient())<x-ui.button href="{{ route('client.ondemand.create') }}">Solicitar chamba ahora <i class="bi bi-arrow-up-right"></i></x-ui.button>@else<x-ui.button href="{{ route(auth()->user()->dashboardRoute()) }}">Ir a mi espacio <i class="bi bi-arrow-up-right"></i></x-ui.button>@endif @else<x-ui.button href="{{ route('register') }}">Solicitar chamba ahora <i class="bi bi-arrow-up-right"></i></x-ui.button>@endauth<a class="ui-button ui-button--outline" href="{{ route('register') }}">Soy profesional</a></div>
            <div class="hero-trust-row"><span><i class="bi bi-patch-check-fill"></i> Profesionales verificados</span><span><i class="bi bi-shield-check"></i> Pagos seguros</span><span><i class="bi bi-hand-thumbs-up-fill"></i> Garantía Chambapp</span></div>
        </div><div class="col-12 col-lg-6"><div class="hero-visual"><img src="{{ asset('images/hero-professional.png') }}" alt="Profesional Chambapp listo para ayudarte"><div class="hero-search-panel"><div class="hero-search-panel__heading"><strong>¿Qué necesitas?</strong><span>×</span></div><label for="hero-category">Servicio</label><div class="hero-search-panel__select" id="hero-category"><i class="bi bi-tools"></i><span>Selecciona una categoría</span><i class="bi bi-chevron-down"></i></div><div class="hero-search-panel__select"><i class="bi bi-geo-alt"></i><span>Mi ubicación actual</span><i class="bi bi-x-circle"></i></div><a class="ui-button ui-button--primary w-100" href="{{ route('marketplace.search') }}">Buscar profesionales</a></div><div class="hero-visual__availability"><span class="hero-visual__dot"></span> Profesionales disponibles cerca de ti</div></div></div></div></div>
    </section>

    <section class="quick-benefits"><div class="container"><div class="row g-3"><div class="col-12 col-md-4"><div class="quick-benefit"><span class="quick-benefit__icon"><i class="bi bi-person-check"></i></span><div><strong>Profesionales verificados</strong><small>Perfiles verificados y calificaciones reales</small></div></div></div><div class="col-12 col-md-4"><div class="quick-benefit"><span class="quick-benefit__icon"><i class="bi bi-credit-card-2-front"></i></span><div><strong>Pagos seguros</strong><small>Paga de forma segura con Mercado Pago</small></div></div></div><div class="col-12 col-md-4"><div class="quick-benefit"><span class="quick-benefit__icon"><i class="bi bi-shield-check"></i></span><div><strong>Garantía Chambapp</strong><small>Tu satisfacción es nuestra prioridad</small></div></div></div></div></div></section>

    <section id="categorias" class="reference-section"><div class="container"><div class="reference-heading"><div><span class="reference-heading__eyebrow">Explora</span><h2>Categorías populares</h2><p>Encuentra profesionales en las categorías más solicitadas</p></div><a href="{{ route('marketplace.categories') }}">Ver todas <i class="bi bi-arrow-up-right"></i></a></div><div class="row g-3">@forelse ($categories as $category)<div class="col-6 col-md-4 col-lg-2"><a class="reference-category" href="{{ route('marketplace.category', $category) }}"><span><i class="bi bi-{{ $category->icon ?: 'grid' }}"></i></span><strong>{{ $category->name }}</strong><small>Profesionales cerca</small></a></div>@empty<div class="col-12"><x-ui.empty-state icon="grid" title="Categorías en preparación" description="Pronto podrás explorar servicios por categoría." /></div>@endforelse</div></div></section>

    <section id="profesionales" class="reference-section reference-section--muted"><div class="container"><div class="reference-heading"><div><span class="reference-heading__eyebrow">Talento confiable</span><h2>Profesionales destacados</h2><p>Personas verificadas que harán posible tu próxima solución</p></div><a href="{{ route('marketplace.search') }}">Buscar profesionales <i class="bi bi-arrow-right"></i></a></div><div class="row g-3 g-lg-4">@forelse ($professionals as $professional)<div class="col-12 col-md-6 col-lg-4"><x-ui.card class="reference-professional-card h-100" padding="lg"><div class="reference-professional-card__top"><x-ui.avatar :user="$professional->user" :src="$professional->profile_photo" :name="$professional->user?->name" size="lg" /><x-ui.badge variant="verified" label="Verificado" /></div><h3>{{ $professional->user?->name ?? 'Profesional Chambapp' }}</h3><p>{{ $professional->bio ?: 'Listo para ayudarte con experiencia y atención cercana.' }}</p><div class="reference-professional-card__meta"><span><i class="bi bi-star-fill"></i> {{ (int) $professional->total_reviews > 0 ? number_format((float) $professional->average_rating, 1) : 'Nuevo' }}</span><span><i class="bi bi-geo-alt"></i> {{ $professional->city ?: 'Cerca de ti' }}</span></div><x-ui.button variant="outline" class="w-100 mt-auto" href="{{ route('professional.public-profile', $professional) }}">Ver perfil</x-ui.button></x-ui.card></div>@empty<div class="col-12"><x-ui.empty-state icon="person-badge" title="Profesionales en preparación" description="Estamos preparando perfiles para que puedas conocerlos." /></div>@endforelse</div></div></section>

    <section id="como-funciona" class="reference-section"><div class="container"><div class="reference-how"><div><span class="reference-heading__eyebrow">Cómo funciona</span><h2>Tu próxima chamba empieza aquí</h2><p>Encuentra, compara y conecta con la persona ideal para resolverlo.</p></div><div class="reference-steps"><div><b>01</b><strong>Cuéntanos qué necesitas</strong><small>Publica tu solicitud en minutos.</small></div><div><b>02</b><strong>Recibe opciones confiables</strong><small>Conoce perfiles y cotizaciones.</small></div><div><b>03</b><strong>Haz que suceda</strong><small>Contrata y da seguimiento.</small></div></div></div></div></section>

    <section class="reference-cta"><div class="container"><div class="reference-cta__inner"><div><span class="reference-heading__eyebrow">Para profesionales</span><h2>¿Tienes una habilidad que compartir?</h2><p>Crea tu perfil, publica tus servicios y encuentra nuevas chambas.</p></div>@guest<x-ui.button href="{{ route('register') }}">Crear cuenta profesional <i class="bi bi-arrow-right"></i></x-ui.button>@else<x-ui.button href="{{ route(auth()->user()->dashboardRoute()) }}">Ir a mi espacio <i class="bi bi-arrow-right"></i></x-ui.button>@endguest</div></div></section>
@endsection
