@extends('layouts.app')
@section('title', 'Programar chamba | Chambapp')
@section('content')
<section class="form-page"><div class="container container--narrow"><a class="text-link" href="{{ route('client.dashboard') }}"><i class="bi bi-arrow-left"></i> Volver</a><div class="page-heading mt-3"><p class="eyebrow">Servicio programado</p><h1 class="page-title">Programa cuándo lo necesitas</h1><p class="text-muted">El profesional recibirá tu solicitud para preparar la cotización.</p></div>@if ($errors->any())<x-ui.alert variant="danger">{{ $errors->first() }}</x-ui.alert>@endif<x-ui.card padding="lg"><form method="POST" action="{{ route('client.scheduled.store') }}">@csrf
    <div class="mb-3"><label class="form-label" for="scheduled-mode">Tipo de solicitud</label><select class="form-select" id="scheduled-mode" name="service_mode" required><option value="scheduled" @selected(old('service_mode', 'scheduled') === 'scheduled')>Servicio programado</option><option value="diagnostic" @selected(old('service_mode') === 'diagnostic')>Cita de diagnóstico</option></select><div class="form-text">El diagnóstico permite revisar tu necesidad antes de definir el trabajo.</div></div>
    <div class="mb-3"><label class="form-label" for="scheduled-category">Categoría</label><select class="form-select" id="scheduled-category" name="category_id" required><option value="">Selecciona una categoría</option>@foreach ($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>
    <div class="mb-3"><label class="form-label" for="scheduled-title">Título</label><input class="form-control" id="scheduled-title" name="title" maxlength="160" required></div><div class="mb-3"><label class="form-label" for="scheduled-description">Descripción</label><textarea class="form-control" id="scheduled-description" name="description" rows="4" maxlength="5000" required></textarea></div>
    <div class="row g-3 mb-3"><div class="col-12 col-sm-6"><label class="form-label" for="scheduled-for">Fecha</label><input class="form-control" id="scheduled-for" name="scheduled_for" type="datetime-local" min="{{ now()->addHour()->format('Y-m-d\TH:i') }}" required></div><div class="col-12 col-sm-6"><label class="form-label" for="scheduled-slot">Horario</label><select class="form-select" id="scheduled-slot" name="scheduled_slot" required><option value="">Selecciona un bloque</option><option value="08:00-11:00">08:00–11:00</option><option value="11:00-14:00">11:00–14:00</option><option value="14:00-17:00">14:00–17:00</option><option value="17:00-20:00">17:00–20:00</option></select></div></div>
    <div class="row g-3 mb-4"><div class="col-12"><label class="form-label" for="scheduled-address">Dirección</label><input class="form-control" id="scheduled-address" name="address" maxlength="255" required></div><div class="col-sm-4"><label class="form-label" for="scheduled-city">Ciudad</label><input class="form-control" id="scheduled-city" name="city" maxlength="100" required></div><div class="col-sm-4"><label class="form-label" for="scheduled-state">Estado</label><input class="form-control" id="scheduled-state" name="state" maxlength="100" required></div><div class="col-sm-4"><label class="form-label" for="scheduled-postal">C.P.</label><input class="form-control" id="scheduled-postal" name="postal_code" maxlength="10" required></div></div>
    <div class="d-flex gap-2"><x-ui.button type="submit">Enviar solicitud</x-ui.button><x-ui.button href="{{ route('client.ondemand.create') }}" variant="outline">Necesito ayuda ahora</x-ui.button></div>
    </form></x-ui.card></div></section>
@endsection
