@extends('layouts.app')
@section('title', 'Cargos | Administración')
@section('content')
<section class="admin-page"><div class="container"><div class="page-heading"><div><p class="eyebrow">Finanzas</p><h1 class="page-title">Cargos Chambapp</h1></div></div>
<x-ui.card class="mb-4" padding="md"><form class="admin-filter-bar" method="GET"><select class="form-select form-select-sm" name="range"><option value="today" @selected($range === 'today')>Hoy</option><option value="7" @selected($range === '7')>Últimos 7 días</option><option value="30" @selected($range === '30')>Últimos 30 días</option><option value="month" @selected($range === 'month')>Este mes</option><option value="custom" @selected($range === 'custom')>Rango personalizado</option></select><input class="form-control form-control-sm" type="date" name="from" value="{{ request('from') }}"><input class="form-control form-control-sm" type="date" name="to" value="{{ request('to') }}"><button class="ui-button ui-button--primary ui-button--sm">Aplicar</button></form></x-ui.card>
<div class="row g-3 mb-4"><div class="col-12 col-md-4"><x-ui.card padding="md"><span>Total cobrado</span><strong>{{ $gross }}</strong></x-ui.card></div><div class="col-12 col-md-4"><x-ui.card padding="md"><span>Ingreso bruto plataforma</span><strong>{{ $fees }}</strong></x-ui.card></div><div class="col-12 col-md-4"><x-ui.card padding="md"><span>Modelo actual</span><strong>{{ $clientFeePercent }}% + {{ $professionalCommissionPercent }}%</strong><small>Solo aplica a operaciones nuevas.</small></x-ui.card></div></div>
<div class="admin-table-wrap"><table class="table admin-table"><thead><tr><th>Trabajo</th><th>Profesional</th><th>Base</th><th>Cargo cliente</th><th>Comisión profesional</th><th>Ingreso bruto plataforma</th><th>Profesional antes de costos</th><th>Fecha</th></tr></thead><tbody>@forelse ($payments as $payment)<tr><td><a href="{{ route('admin.payments.show', $payment) }}">#{{ $payment->job_request_id }}</a></td><td>{{ $payment->professional->user->name }}</td><td>{{ $payment->base_amount ?? $payment->gross_amount }}</td><td>{{ $payment->client_service_fee ?? '0.00' }}</td><td>{{ $payment->professional_commission_percent ?? $payment->platform_fee_percent }}% · {{ $payment->professional_commission ?? $payment->platform_fee }}</td><td>{{ $payment->platform_gross_fee ?? $payment->platform_fee }}</td><td>{{ $payment->professional_amount_before_external_costs ?? $payment->professional_amount }}</td><td>{{ $payment->paid_at?->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="8">Sin pagos aprobados en el periodo.</td></tr>@endforelse</tbody></table></div>
@if ($payments->hasPages())<div class="mt-4"><x-pagination :paginator="$payments" /></div>@endif
</div></section>
@endsection
