@if ($isClient && $jobRequest->status === \App\Enums\JobStatus::AWAITING_CONFIRMATION)
    <x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Verificacion del servicio</p><h2 class="job-section-title">Comparte el codigo con el prestador</h2><p class="text-muted">Revisa el trabajo. Si todo esta correcto, entrega este codigo al prestador para que lo valide en su cuenta.</p><div class="display-5 text-center fw-bold py-3">{{ $jobRequest->completion_code }}</div></x-ui.card>
    <x-ui.card class="mt-4 dispute-card" padding="lg"><p class="eyebrow mb-2">Algo no salio bien?</p><h2 class="job-section-title">Reportar un problema</h2><p class="text-muted">El caso sera revisado por Chambapp antes de completar el servicio.</p><form method="POST" action="{{ route('job-requests.dispute', $jobRequest) }}">@csrf<div class="mb-3"><label class="form-label" for="dispute-reason">Motivo</label><select class="form-select" id="dispute-reason" name="reason" required><option value="">Selecciona un motivo</option><option value="incomplete_work">Trabajo incompleto</option><option value="not_as_agreed">El servicio no coincide con lo acordado</option><option value="damage_or_issue">Dano o problema durante el trabajo</option><option value="professional_absent">El profesional no acudio</option><option value="other">Otro</option></select></div><div class="mb-3"><label class="form-label" for="dispute-description">Descripcion <span class="text-muted">(opcional)</span></label><textarea class="form-control" id="dispute-description" name="description" maxlength="1000" rows="4"></textarea></div><x-ui.button class="w-100" variant="danger" type="submit">Reportar problema</x-ui.button></form></x-ui.card>
@elseif ($isClient && $jobRequest->status === \App\Enums\JobStatus::COMPLETED)
    <x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Tu experiencia</p>@if ($canReview)<h2 class="job-section-title">Como fue el servicio?</h2><p class="text-muted">Comparte una calificacion y, si quieres, una propina.</p><div class="d-flex flex-column gap-2"><a class="ui-button ui-button--primary w-100" href="{{ route('reviews.create', $jobRequest) }}"><i class="bi bi-star" aria-hidden="true"></i> Calificar profesional</a><form class="row g-2" method="POST" action="{{ route('job-requests.tip', $jobRequest) }}">@csrf<div class="col"><label class="visually-hidden" for="tip-amount">Propina</label><input class="form-control" id="tip-amount" name="amount" type="number" min="1" max="99999.99" step="0.01" placeholder="Propina en MXN"></div><div class="col-auto"><x-ui.button variant="outline" type="submit">Agregar propina</x-ui.button></div></form></div>@else<h2 class="job-section-title">Resena publicada</h2><p class="text-muted mb-0">Gracias por compartir tu experiencia.</p>@endif</x-ui.card>
@elseif (! $isClient && $jobRequest->status === \App\Enums\JobStatus::AWAITING_CONFIRMATION)
    <x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Codigo del cliente</p><h2 class="job-section-title">Valida la finalizacion</h2><p class="text-muted">Pide al cliente el codigo que aparece en su cuenta e introducelo para liberar el trabajo.</p><form method="POST" action="{{ route('job-requests.complete', $jobRequest) }}">@csrf<div class="mb-3"><label class="form-label" for="completion-code">Codigo de 6 digitos</label><input class="form-control form-control-lg text-center" id="completion-code" name="completion_code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></div><x-ui.button class="w-100" type="submit">Validar y completar trabajo</x-ui.button></form></x-ui.card>
@elseif ($jobRequest->status === \App\Enums\JobStatus::DISPUTED)
    <x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Revision de Chambapp</p><h2 class="job-section-title">Trabajo en disputa</h2><p class="text-muted mb-0">El caso fue recibido y sera revisado antes de liberar el cierre.</p></x-ui.card>
@endif
@if ($jobRequest->review)<x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Resena del cliente</p><x-review-card :review="$jobRequest->review" /></x-ui.card>@endif
