@if ($isClient && $jobRequest->status === \App\Enums\JobStatus::AWAITING_CONFIRMATION && $canDispute)
    <x-ui.card class="mt-4 dispute-card" padding="lg"><p class="eyebrow mb-2">¿Algo no salió bien?</p><h2 class="job-section-title">Reportar un problema</h2><p class="text-muted">El caso será revisado por Chambapp. Esta acción no genera reembolso automático.</p><form method="POST" action="{{ route('job-requests.dispute', $jobRequest) }}">@csrf<div class="mb-3"><label class="form-label" for="dispute-reason">Motivo</label><select class="form-select" id="dispute-reason" name="reason" required><option value="">Selecciona un motivo</option><option value="incomplete_work">Trabajo incompleto</option><option value="not_as_agreed">El servicio no coincide con lo acordado</option><option value="damage_or_issue">Daño o problema durante el trabajo</option><option value="professional_absent">El profesional no acudió</option><option value="other">Otro</option></select></div><div class="mb-3"><label class="form-label" for="dispute-description">Descripción <span class="text-muted">(opcional)</span></label><textarea class="form-control" id="dispute-description" name="description" maxlength="1000" rows="4" placeholder="Cuéntanos brevemente qué ocurrió."></textarea></div><x-ui.button class="w-100" variant="danger" type="submit">Reportar problema</x-ui.button></form></x-ui.card>
@elseif ($isClient && $jobRequest->status === \App\Enums\JobStatus::COMPLETED)
    <x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Tu experiencia</p>@if ($canReview)<h2 class="job-section-title">¿Cómo fue el servicio?</h2><p class="text-muted">Comparte una calificación para ayudar a otros clientes.</p><a class="ui-button ui-button--primary w-100" href="{{ route('reviews.create', $jobRequest) }}"><i class="bi bi-star" aria-hidden="true"></i> Calificar profesional</a>@else<h2 class="job-section-title">Reseña publicada</h2><p class="text-muted mb-0">Gracias por compartir tu experiencia.</p>@endif</x-ui.card>
@elseif (! $isClient && $jobRequest->status === \App\Enums\JobStatus::AWAITING_CONFIRMATION)
    <x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Siguiente paso</p><h2 class="job-section-title">Esperando confirmación del cliente</h2><p class="text-muted mb-0">El cliente recibió una notificación para revisar el trabajo.</p></x-ui.card>
@elseif ($jobRequest->status === \App\Enums\JobStatus::DISPUTED)
    <x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Revisión de Chambapp</p><h2 class="job-section-title">Trabajo en disputa</h2><p class="text-muted mb-0">El caso fue recibido. No se ha generado ningún reembolso automático.</p></x-ui.card>
@endif
@if ($jobRequest->review)<x-ui.card class="mt-4" padding="lg"><p class="eyebrow mb-2">Reseña del cliente</p><x-review-card :review="$jobRequest->review" /></x-ui.card>@endif
