@extends('layouts.app')

@section('title', 'Contratar servicio | Chambapp')

@section('content')
    <section class="job-page"><div class="container"><div class="page-heading"><div><p class="eyebrow mb-2"><i class="bi bi-shield-check" aria-hidden="true"></i> Contratación directa</p><h1 class="page-title">Contratar este servicio.</h1><p class="section-copy mb-0">Confirma los detalles de tu contratación antes de proceder al pago.</p></div></div>
        <div class="row g-4 g-lg-5"><div class="col-12 col-lg-5"><x-ui.card class="job-service-summary h-100" padding="lg"><span class="service-card__category">{{ $service->category->name }}</span><h2 class="h4 mt-3 mb-2">{{ $service->title }}</h2><p class="text-muted mb-3">{{ $service->description }}</p><div class="job-service-summary__professional"><x-ui.avatar :user="$service->professional->user" :src="$service->professional->profile_photo" :name="$service->professional->user->name" size="md" /><div><span class="small text-muted d-block">Profesional</span><strong>{{ $service->professional->user->name }}</strong></div></div><div class="job-service-summary__price mt-4">Precio del servicio: <strong>{{ $service->formattedPrice() }}</strong></div></x-ui.card></div>
            <div class="col-12 col-lg-7"><x-ui.card padding="lg"><form method="POST" action="{{ route('job-requests.store', $service) }}">@csrf @if ($errors->any())<x-ui.alert variant="danger" title="Revisa los datos">Hay campos que necesitan atención.</x-ui.alert>@endif
                <div class="job-form-section"><h2 class="job-form-section__title">Detalles del trabajo</h2><div class="mb-3"><label class="form-label" for="job-title">Título o resumen</label><input class="form-control @error('title') is-invalid @enderror" id="job-title" name="title" value="{{ old('title', $service->title) }}" maxlength="160" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="mb-3"><label class="form-label" for="job-description">¿Qué necesitas?</label><textarea class="form-control @error('description') is-invalid @enderror" id="job-description" name="description" rows="5" maxlength="5000" required>{{ old('description') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div><label class="form-label" for="requested-date">Fecha deseada</label><input class="form-control @error('requested_date') is-invalid @enderror" id="requested-date" name="requested_date" type="datetime-local" value="{{ old('requested_date') }}" min="{{ now()->format('Y-m-d\TH:i') }}" required><div class="form-text">Elige una fecha y hora a partir de ahora.</div>@error('requested_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
                <div class="job-form-section"><h2 class="job-form-section__title">Dónde realizarlo</h2><div class="mb-3"><label class="form-label" for="job-address">Dirección</label><input class="form-control @error('address') is-invalid @enderror" id="job-address" name="address" value="{{ old('address') }}" maxlength="255" required>@error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="row g-3"><div class="col-12 col-md-5"><label class="form-label" for="job-city">Ciudad</label><input class="form-control @error('city') is-invalid @enderror" id="job-city" name="city" value="{{ old('city') }}" maxlength="100" required>@error('city')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12 col-md-4"><label class="form-label" for="job-state">Estado</label><input class="form-control @error('state') is-invalid @enderror" id="job-state" name="state" value="{{ old('state') }}" maxlength="100" required>@error('state')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12 col-md-3"><label class="form-label" for="job-postal-code">C.P.</label><input class="form-control @error('postal_code') is-invalid @enderror" id="job-postal-code" name="postal_code" value="{{ old('postal_code') }}" maxlength="10" required>@error('postal_code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
                <div class="d-flex flex-column flex-sm-row justify-content-end gap-2 mt-4"><a class="ui-button ui-button--link" href="{{ route('marketplace.service', $service) }}">Volver al servicio</a><x-ui.button type="submit"><i class="bi bi-arrow-right-circle" aria-hidden="true"></i> Confirmar y proceder al pago</x-ui.button></div>
            </form></x-ui.card></div></div>
    </div></section>
@endsection
